#----------- name ----------#
name: m_auto
description: "A new Flutter project."

#----------- publish ----------#
publish_to: 'none' 

#----------- version ----------#
version: 1.0.0+1

#----------- environment ----------#
environment:
  sdk: ^3.5.4

#----------- dependencies ----------#
dependencies:
  flutter:
    sdk: flutter


  #----------- packages ----------#
  # icons
  cupertino_icons: ^1.0.8
  # screen util
  flutter_screenutil: ^5.9.3
  # bloc
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  # dio
  dio: ^5.7.0
  # logger
  pretty_dio_logger: ^1.3.0
  # app translation
  flutter_localizations:
    sdk: flutter
  # intl
  intl: ^0.19.0
  # Shared Preferences
  shared_preferences: ^2.3.3
  # animations
  animations: ^2.0.11


#----------- dev_dependencies ----------#
dev_dependencies:
  flutter_test:
    sdk: flutter

    
  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  #----------- assets ----------#
  assets:
    - assets/images/


  #----------- fonts ----------#
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # 
